### ISSUE TITLE
get all parameters doesn't update values

### ISSUE THREAD

**Issue by rickaha** [RISE-Dependable-Transport-Systems/WayWise#72]
**Describe the bug**
Param::AllParams mavsdk::Param::get_all_params() doesn't retreive the updated values, but requests on specific parameter values with for example std::pair<Result, int32_t> get_param_int(std::string name) does.

**To Reproduce**
1. Open ControlTower and RCCar
2. Click on 'Vehicle Parameters' and then 'Get Parameters From Vehicle'. Change a value and then click 'Set New...'. If you now click 'Get Param...' the list will update and your newly set value will return to old value

**Expected behavior**
Clicking 'Get Parameter...' should display the current values, including your newly changed one

**Screenshots**
![Screenshot from 2024-02-01 11-23-53](https://github.com/RISE-Dependable-Transport-Systems/WayWise/assets/76961018/e74955ed-10d1-44e9-ab10-2a99b40d6798)

**System (please complete the following information):**
 - Hardware: [Desktop]
 - OS: [Ubuntu Linux]
 - Version [22.04]

**Additional context**
Seems MAVSDK has had problems with the Param::AllParams mavsdk::Param::get_all_params() function for quite some time 
https://github.com/mavlink/MAVSDK/issues/1805
https://github.com/mavlink/MAVSDK/issues/2100

There has also been a refactoring lately
https://github.com/mavlink/MAVSDK/pull/1772

I made a temporary fix that's to be removed when this is resolved
https://github.com/RISE-Dependable-Transport-Systems/WayWise/commit/636d308a02d03c340fc8761ebfac627d44127961

**Comment by julianoes** [comment]
:wave: hello, just saw this issue linked.

This should be fixed with https://github.com/mavlink/MAVSDK/pull/2457.
